### PR TITLE
Various PDB fixes

### LINKED ISSUE #68: Fix PDB files
Essentially #58 but this time directly against `main`.

Need to fix:
- Make sure HETATM are applied properly, and make sure https://github.com/openforcefield/protein-ligand-benchmark/pull/52#issuecomment-1259610322 is fixed.
- Change the atom names for the caps to adhere to PDB naming conventions
- Remove ANISOU records for TYK2 and Thrombin
- Rename NMA caps to NME
- Don't have NME (or NMA) caps have icodes
- Make sure SSBOND entries are consistent (I believe this is already fine)
- Assign correct hydrogen name for histidines (need to double check if this is PDB compliant)

### PR DESCRIPTION
**Pull request by IAlibay**
Fixes #68 

TODO:
- [x] Make sure HETATM are applied properly, and make sure https://github.com/openforcefield/protein-ligand-benchmark/pull/52#issuecomment-1259610322 is fixed.
- [x] Change the atom names for the caps to adhere to PDB naming conventions
- [x] Remove ANISOU records for TYK2 and Thrombin
- [x] Rename NMA caps to NME
- [x] Don't have NME (or NMA) caps have icodes
- [x] Rename first residue backbone hydrogen to correct naming scheme
- [x] Make sure SSBOND entries are consistent - CONECT records for thrombin are there and it's all consistent with pdb4amber
- [x] Fix `pfkfb3` connection record
- [x] Remove CONECT records for caps
- [x] Work out what to do with TPO in cdk2 - double check CCD entry
- [x] TNSK2, and PDE2 with bonded zinc and PDE2 with bonded magnesium?
    - [x] Shift to LINKS

### CODE REVIEW

**Comment by dotsdl** [comment]
@IAlibay will remove CONECT records for now; may re-add in 0.4.0

**Comment by dotsdl** [comment]
For structural ions, let's use LINKS entries to indicate their coordination.

**Review by jchodera — APPROVED** [review]
These changes look good to me!

I've confirmed the protein PDB files can all be read in OpenMM:
```
from openmm.app import PDBFile

from glob import glob
filenames = glob('data/*/01_*/crd/*.pdb')
print(filenames)

# Define the keyword arguments to feed to ForceField
from openmm import unit
from openmm import app
forcefield_kwargs = { 'constraints' : app.HBonds, 'rigidWater' : True, 'removeCMMotion' : False, 'hydrogenMass' : 4*unit.amu }
# Initialize a SystemGenerator using GAFF
from openmmforcefields.generators import SystemGenerator
system_generator = SystemGenerator(forcefields=['amber/ff14SB.xml', 'amber/phosaa14SB.xml', 'amber/tip3p_standard.xml'], small_molecule_forcefield='gaff-2.11', forcefield_kwargs=forcefield_kwargs, cache='db.json')

for filename in filenames:
    print(filename)
    pdbfile = app.PDBFile(filename)
    openmm_topology = pdbfile.topology
    # Create an OpenMM System from an OpenMM Topology object
    system = system_generator.create_system(openmm_topology)
```

**Comment by IAlibay** [comment]
Thanks for the review @jchodera !

**Pull request merged**
