### PR TITLE
Add two more targets, ros1 and pde10

### PR DESCRIPTION
**Pull request by dfhahn**

### CODE REVIEW

**Comment by dotsdl** [comment]
I'll review; will ask for two other folks to give targets a look as well.

**Comment by dotsdl** [comment]
From @ppxasjsm: ideally we want to know that the systems are runnable with an MD engine, such as a minimization on each. Probably not possible to do direct visualization of each structure.

From @IAlibay: just being able to pass PDB files through OpenMM PDBFile could help us here. Can point you to an MDAnalysis snippet that does some sanity-checks.

From @dotsdl: we may need to run these through the same solution used for solving #20. I will identify problem cases from @IAlibay's suggestion, then loop in @bobym for those problem cases.

**Comment by IAlibay** [comment]
Further from today's meeting @dotsdl here's what I'm using to quickly look for clashes in the structures (mixing RDKit loading into MDA etc... [can send the full script off-github]): https://github.com/IAlibay/CheckStructure

**Review by dotsdl — COMMENTED** [review]
Thank you for putting this together @dfhahn! Overall looks good, but a few notes. Jupyter notebook attached with the details.

1. Both `ros1` and `pde10` can be parsed by OpenMM `PDBFile`.
2. All ligands for both targets can be parameterized with OpenFF 2.0.0.
3. Ligands for `ros1` and `pde10` are aligned nearly as much as possible on their maximum common substructure given their chosen conformations.
4. There are clashes for the following targets with `ros1`:
    - lig_4326.sdf: clashes with F167 and a L150
    - lig_8654.sdf: clashes with L15

@dfhahn what approach did you take to get past the clashes observed here? Any suggestions on the best approach to remediate?

[PR-45.zip](https://github.com/openforcefield/protein-ligand-benchmark/files/8759487/PR-45.zip)

**Pull request merged**
