### PR TITLE
Remove `ros1` as a target

### PR DESCRIPTION
**Pull request by dotsdl**
Since `ros1` is not based on a structure with a PDB code, we propose removing it via this PR.

### CODE REVIEW

**Comment by dotsdl** [comment]
Since [ros1 also contained a couple clashing ligands](https://github.com/openforcefield/protein-ligand-benchmark/pull/45#pullrequestreview-982572614), this obviates the need to fix those as well.

**Comment by dotsdl** [comment]
@ldamore or @IAlibay, can I get a review on this? Should be straightforward since we're just wholesale deleting `ros1`, but want a critical eye on the approach in case I'm too cavalier here.

**Comment by richardjgowers** [comment]
@dotsdl I think #18 is the future of this package, else you'll always have to make decisions on if a dataset is worth its size for including. ~100mb is pretty big if you just wanted one system out.

**Comment by dotsdl** [comment]
@richardjgowers ah yes, fair enough. Yes, in favor of the #18 approach. We have that slated for [Release 0.4.0](https://github.com/openforcefield/protein-ligand-benchmark/milestone/3).

**Pull request merged**
